name: movie_info
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  test: ^1.24.9
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  youtube_player_flutter: ^8.1.2
  share_plus: ^7.2.1
  flutter_native_splash: ^2.3.7
  hive: ^2.2.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo_Icon.png


  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#1F1D2B"
  image: 'assets/images/logo_splash.png'

flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900

